/**
 * Frozen audit captures, not generated by the shared NAV implementation.
 * Reference UI: RealtimeNavViewer.tsx at
 * f2fe5631b04c652c2923c22f09c4cfa3b65df2ad (before extraction).
 * Amounts below are unrounded calculation results; the UI rounds only for display.
 */
const IDS = {
  AISS: 'SPST0Z57G0G', BDC: 'SPST4OZY6KQ', AEUS: 'SPSTJQV96C7',
  MTFS: 'SPSTJZ54GCF', SSRS: 'SPSTWGX9THG', MRPT: 'SPSTWPVC13D',
};

export const frozenMirror = {
  scalars: {
    mrpt: 0.59242525, mtfs: 0.38136643, aiss: 2.68155435,
    ssrs: 0.9950436, bdc: 1, aeus: 1.16116774,
  },
  capital_base: { mrpt: 424265.6299999999, mtfs: 585005.91 },
  cohorts: {},
  scaled_frozen: true,
  rolloff: {
    frozen_at: '2026-09-01T14:10:19+00:00', measured_on: '2026-08-31',
    k_equity: -12004.77, qc_equity: 5681616.62, panel_official_total: 5669611.85,
  },
};

export const midnightOfficial = {
  mrpt: { date: '2026-09-04', value: 611098.38 },
  mtfs: { date: '2026-09-04', value: 328592.72 },
  ssrs: { date: '2026-09-04', value: 1032631.92 },
  aiss: { date: '2026-09-04', value: 2859258.01 },
  aeus: { date: '2026-09-04', value: 1175360.63 },
  bdc: { date: '2026-09-04', value: 940644.52 },
};

function strategy(name: keyof typeof IDS, value: number, day_return: number) {
  return {
    node_id: IDS[name], display_name: name, kind: 'strategy', value, day_return,
    parent_id: 'SPPF96UGK55', holdings: [],
    positions_as_of: ['AISS', 'SSRS', 'AEUS'].includes(name) ? '2026-09-08' : '2026-09-04',
  };
}

// nav_stream_20260909.csv, 2026-09-09 01:53:55 ET, six strategy rows
// 2315/2316/2320/2328/2329/2331; each published day_return was exactly zero.
export const midnightLatest = {
  ts: '2026-09-09T05:53:55+00:00', structure_hash: '5bbf08a2d7bc30eb',
  stale: false, market: 'closed', feed_delay_min: null, missing: [],
  rebuild_error: null, rebuild_error_age_s: null,
  nodes: [
    strategy('AISS', 1095709.48, 0), strategy('BDC', 932874.57, 0),
    strategy('AEUS', 1022452.02, 0), strategy('MTFS', 929159.99, 0),
    strategy('SSRS', 1032742.72, 0), strategy('MRPT', 1034793.19, 0),
    { node_id: 'SPPF96UGK55', display_name: 'PORTFOLIO', kind: 'portfolio',
      value: 6047731.97, day_return: 0 },
  ],
};

export const midnightPrevClose = {
  date: '20260908',
  values: Object.fromEntries(midnightLatest.nodes.map(n => [n.node_id, n.value])),
};

export const midnightExpected = {
  main: 7040623.067734664,
  officialBase: 6947586.18,
  pct: 1.339125349786796,
  oldFormulaTotal: 6947586.18,
  perStrategy: {
    AISS: 2938204.522430238, BDC: 932874.57, AEUS: 1187238.3013218348,
    MTFS: 344154.07999999996, SSRS: 1027624.033982592, MRPT: 610527.56,
  },
};

export const intradayOfficial = {
  mrpt: { date: '2026-09-08', value: 610527.56 },
  mtfs: { date: '2026-09-08', value: 344154.08 },
  ssrs: { date: '2026-09-08', value: 1027624.04 },
  aiss: { date: '2026-09-08', value: 2938204.52 },
  aeus: { date: '2026-09-08', value: 1187238.3 },
  bdc: { date: '2026-09-08', value: 932874.57 },
};

export const intradayLatest = {
  ...midnightLatest,
  ts: '2026-09-09T18:29:17+00:00', market: 'open', feed_delay_min: 15,
  nodes: [
    strategy('AISS', 1096832.8, 0.001025), strategy('BDC', 935267.45, 0.002565),
    strategy('AEUS', 1013685.92, -0.008574), strategy('MTFS', 950537.67, 0.024909),
    strategy('SSRS', 1029240.55, -0.003391), strategy('MRPT', 1035291.32, 0.000633),
  ],
};

export const intradayExpected = {
  main: 7054240.276996881,
  officialBase: 7040623.07,
  pct: 0.1934091182199893,
  oldFormulaTotal: 7041322.496525411,
  perStrategy: {
    AISS: 2941216.76606268, BDC: 935267.45, AEUS: 1177059.3887962208,
    MTFS: 365531.76, SSRS: 1024139.22213798, MRPT: 611025.6900000001,
  },
};
